### ISSUE TITLE
Adding accounts implementation

### ISSUE THREAD

**Issue by stevezhu** [stuycs-softdev-fall-2013/proj3-6-finance#7]
meaning the accounts on the sidebar

**Comment by jasper-lu** [comment]
l0l steve

**Comment by jasper-lu** [comment]
Go away chuk no one likes you

**Comment by devChuk** [comment]
Guys we need to add accounts implementation in the sidebar

**Comment by rogerli** [comment]
If you really believe that, you should get working on it then.
